apiVersion: v1
kind: ReplicationController
metadata:
  name: rchttpd
spec:
  replicas: 4
  selector:
    app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
      - name: httpd
        image: raghudevops26/httpd:v2
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
        env:
         - name: TOMCAT_IP
           value: XYZ

