---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: student-prod
spec:
  containers:
    - name: httpd
      image: httpd
...
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  namespace: student-prod
spec:
  containers:
    - name: httpd
      image: httpd
...
