apiVersion: v1
kind: Pod
metadata:
  name: secret1
spec:
  containers:
  - name: httpd
    image: raghudevops26/httpd
    command:
     - "env"
    env:
      - name: TOMCAT_IP
        valueFrom:
          secretKeyRef:
            name: pass1
            key: pass1
  restartPolicy: Never
